version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: 'programs/mango-v4'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    commit-message:
      prefix: 'v4'
    open-pull-requests-limit: 5
    label:
      - 'cargo'
      - 'dependency'
      
  - package-ecosystem: 'cargo'
    directory: 'programs/margin-trade'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    commit-message:
      prefix: 'margin'
    open-pull-requests-limit: 5
    label:
      - 'cargo'
      - 'dependency'
