name: Publish to Docker

on:
  push:
    branches: [mc/docker]
  workflow_call:
    secrets:
      GCR_PROJECT:
        required: true
      GCR_SA_KEY:
        required: true

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  IMAGE: mango-v4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Login to GCR
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SA_KEY }}

      # Use docker buildx
      - name: Use docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      # Build and push the image, leveraging layer caching
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}
            gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
